import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/context/user-context";
import { I18nProvider, LocalizationProvider } from "@/locales";
import { detectLanguage } from "@/locales/server";
import { NoSSR } from "@/components/no-ssr";
import { CookieConsent } from "@/components/cookie";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Airisto",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.ico",
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = await detectLanguage();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider lang={lang!}>
          <LocalizationProvider>
            <UserProvider>
              <NoSSR>
                {children}
              </NoSSR>
              <Toaster />
              <CookieConsent delay={5000} />
            </UserProvider>
          </LocalizationProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
