import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/context/user-context";
import { I18nProvider, LanguageValue, LocalizationProvider } from "@/locales";
import { CONFIG } from "@/config-global";
import { detectLanguage } from "@/locales/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Airisto",
  description: "Generated by create next app",
  icons: {
    icon: "/airisto.ico",
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = await detectLanguage();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider lang={CONFIG.isStaticExport ? undefined : (lang ?? 'tr') as LanguageValue | undefined}>
          <LocalizationProvider>
            <UserProvider>
              {children}
              <Toaster />
            </UserProvider>
          </LocalizationProvider>
        </I18nProvider>

      </body>
    </html>
  );
}
